[book]
title = "Scopeuk's 3D Printing Notes"

[preprocessor.index]

[preprocessor.links]

[output.html.search]
limit-results = 15

[preprocessor.pagetoc]
[output.html]
git-repository-url = "https://github.com/Scopeuk/3dPrintingNotes"
site-url = "/3dPrintingNotes/"
